config/routes.rb
Bendylunch::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :restaurants, only: :index do
    collection do
      match '/:tag' => 'restaurants#random', as: 'tagged'
    end
  end

  root to: "restaurants#random"
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  acts_as_taggable

  attr_accessible :name, :tag_ids, :tag_list

  validates :name,
    presence: true,
    uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  respond_to :html, :json
  before_filter :find_random_restaurant, only: :random

  def random
    respond_with @restaurant
  end

  def index
    @restaurants = Restaurant.all
    respond_with @restaurants
  end

  private

  def find_random_restaurant
    relation = params[:tag] ? Restaurant.tagged_with(params[:tag]) : Restaurant

    @restaurant = relation.first(order: 'RANDOM()') || Restaurant.new(name: 'the kitchen')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Bendylunch
    = stylesheet_link_tag 'application', :media => 'screen, projection'
    = stylesheet_link_tag 'print', :media => 'print'
    /[if lt IE 8]
      = stylesheet_link_tag 'ie', :media => 'screen, projection'
    = javascript_include_tag "application"
    = csrf_meta_tags
    = render partial: '/google_analytics'
  %body
    = yield

app/views/restaurants/_tag.html.haml
%li.tag
  = link_to(tag.name, tagged_restaurants_path(tag.name))

app/views/restaurants/random.html.haml
.restaurant.afs-pt-serif
  You should go to
  %h1.afs-ubuntu
    = @restaurant.name
  %ul.tags
    = render partial: 'tag', collection: @restaurant.tags